In [2]:
from bitarray import bitarray
import mmh3
import random
import numpy as np
import math
import sklearn.preprocessing

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

/Users/aditijain/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/aditijain/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/aditijain/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/aditijain/opt/anaconda3/lib/python3.7/site-packages

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler 
import pandas as pd

In [38]:
file = pd.read_csv("/Users/aditijain/Desktop/NewFolderWithItems/facebook-v-predicting-check-ins/train.csv")
file.head()


row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949

In [39]:
file.values

array([[0.00000000e+00, 7.94100000e-01, 9.08090000e+00, 5.40000000e+01,
        4.70702000e+05, 8.52306562e+09],
       [1.00000000e+00, 5.95670000e+00, 4.79680000e+00, 1.30000000e+01,
        1.86555000e+05, 1.75772671e+09],
       [2.00000000e+00, 8.30780000e+00, 7.04070000e+00, 7.40000000e+01,
        3.22648000e+05, 1.13753724e+09],
       ...,
       [2.91180180e+07, 2.99930000e+00, 6.36800000e+00, 6.70000000e+01,
        7.37758000e+05, 2.83833430e+09],
       [2.91180190e+07, 4.06370000e+00, 8.00610000e+00, 7.00000000e+01,
        7.64975000e+05, 1.00735585e+09],
       [2.91180200e+07, 7.45230000e+00, 2.08710000e+00, 1.70000000e+01,
        1.02842000e+05, 7.02869813e+09]])

In [15]:
for col in file.columns:
    print(col)

row_id
x
y
accuracy
time
place_id


In [32]:
x_train = np.array(file.values[:,1:-1])
print(x_train[0:4])

[[7.94100e-01 9.08090e+00 5.40000e+01 4.70702e+05]
 [5.95670e+00 4.79680e+00 1.30000e+01 1.86555e+05]
 [8.30780e+00 7.04070e+00 7.40000e+01 3.22648e+05]
 [7.36650e+00 2.51650e+00 6.50000e+01 7.04587e+05]]


In [33]:
x_train.shape

(29118021, 4)

In [35]:
y_train = np.array(file.values[:,-1]).reshape(-1,1)
print(y_train[0:4])

[[8.52306562e+09]
 [1.75772671e+09]
 [1.13753724e+09]
 [6.56739324e+09]]


In [36]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [37]:
x_train

array([[-1.47174853,  1.4126682 , -0.25140462,  0.23225422],
       [ 0.33487188, -0.07100038, -0.60869758, -0.99688213],
       [ 1.157625  ,  0.70610658, -0.07711537, -0.40818384],
       ...,
       [-0.70005223,  0.47313726, -0.13811661,  1.38745993],
       [-0.32757193,  1.0404437 , -0.11197322,  1.50519267],
       [ 0.85824799, -1.00942309, -0.57383973, -1.35899994]])

In [47]:
f = lambda x: x % 23 
g=lambda x: x%2

In [45]:
y_train=f(y_train)

In [46]:
y_train[0:4]

array([[15.],
       [13.],
       [15.],
       [ 8.]])

In [48]:
y_train=g(y_train)

In [49]:
y_train[0:4]

array([[1.],
       [1.],
       [1.],
       [0.]])